# Auto-generated by tools/gen_tileset.py. Do not edit by hand.
class_name TileIds
extends RefCounted

const SOURCE_ID: int = 0

const BLD_C_L1 := Vector2i(4, 9)
const BLD_I_L1 := Vector2i(5, 9)
const BLD_R_L1 := Vector2i(3, 9)
const DIRT := Vector2i(5, 0)
const GRASS := Vector2i(0, 0)
const HYDRO := Vector2i(8, 18)
const ICON_BULLDOZE := Vector2i(0, 31)
const ICON_FLOOD := Vector2i(2, 32)
const ICON_OVERLAY_CRIME := Vector2i(3, 31)
const ICON_OVERLAY_LV := Vector2i(4, 31)
const ICON_OVERLAY_OFF := Vector2i(1, 31)
const ICON_OVERLAY_POLL := Vector2i(2, 31)
const ICON_OVERLAY_POWER := Vector2i(5, 31)
const ICON_OVERLAY_SEWER := Vector2i(7, 31)
const ICON_OVERLAY_TRAFFIC := Vector2i(3, 32)
const ICON_OVERLAY_WATER := Vector2i(6, 31)
const ICON_QUAKE := Vector2i(1, 32)
const ICON_TORNADO := Vector2i(0, 32)
const NO_POWER_IND := Vector2i(5, 18)
const NO_WATER_IND := Vector2i(6, 18)
const OVERLAY_0 := Vector2i(0, 18)
const OVERLAY_1 := Vector2i(1, 18)
const OVERLAY_2 := Vector2i(2, 18)
const OVERLAY_3 := Vector2i(3, 18)
const OVERLAY_4 := Vector2i(4, 18)
const PARK := Vector2i(6, 9)
const RUBBLE := Vector2i(7, 0)
const TREE := Vector2i(6, 0)
const WATER := Vector2i(1, 0)
const WATER_TOWER := Vector2i(9, 18)
const WIND := Vector2i(7, 18)
const ZONE_C := Vector2i(1, 9)
const ZONE_I := Vector2i(2, 9)
const ZONE_R := Vector2i(0, 9)

const ARCO_DARCO: Array[Vector2i] = [Vector2i(0, 28), Vector2i(1, 28), Vector2i(2, 28), Vector2i(0, 29), Vector2i(1, 29), Vector2i(2, 29), Vector2i(0, 30), Vector2i(1, 30), Vector2i(2, 30)]
const ARCO_FOREST: Array[Vector2i] = [Vector2i(6, 25), Vector2i(7, 25), Vector2i(8, 25), Vector2i(6, 26), Vector2i(7, 26), Vector2i(8, 26), Vector2i(6, 27), Vector2i(7, 27), Vector2i(8, 27)]
const ARCO_LAUNCH: Array[Vector2i] = [Vector2i(3, 28), Vector2i(4, 28), Vector2i(5, 28), Vector2i(3, 29), Vector2i(4, 29), Vector2i(5, 29), Vector2i(3, 30), Vector2i(4, 30), Vector2i(5, 30)]
const ARCO_PLYMOUTH: Array[Vector2i] = [Vector2i(3, 25), Vector2i(4, 25), Vector2i(5, 25), Vector2i(3, 26), Vector2i(4, 26), Vector2i(5, 26), Vector2i(3, 27), Vector2i(4, 27), Vector2i(5, 27)]
const BLD_C_L2: Array[Vector2i] = [Vector2i(2, 10), Vector2i(3, 10), Vector2i(2, 11), Vector2i(3, 11)]
const BLD_C_L3: Array[Vector2i] = [Vector2i(3, 15), Vector2i(4, 15), Vector2i(5, 15), Vector2i(3, 16), Vector2i(4, 16), Vector2i(5, 16), Vector2i(3, 17), Vector2i(4, 17), Vector2i(5, 17)]
const BLD_I_L2: Array[Vector2i] = [Vector2i(4, 10), Vector2i(5, 10), Vector2i(4, 11), Vector2i(5, 11)]
const BLD_I_L3: Array[Vector2i] = [Vector2i(6, 15), Vector2i(7, 15), Vector2i(8, 15), Vector2i(6, 16), Vector2i(7, 16), Vector2i(8, 16), Vector2i(6, 17), Vector2i(7, 17), Vector2i(8, 17)]
const BLD_R_L2: Array[Vector2i] = [Vector2i(0, 10), Vector2i(1, 10), Vector2i(0, 11), Vector2i(1, 11)]
const BLD_R_L3: Array[Vector2i] = [Vector2i(0, 15), Vector2i(1, 15), Vector2i(2, 15), Vector2i(0, 16), Vector2i(1, 16), Vector2i(2, 16), Vector2i(0, 17), Vector2i(1, 17), Vector2i(2, 17)]
const COAL: Array[Vector2i] = [Vector2i(0, 12), Vector2i(1, 12), Vector2i(0, 13), Vector2i(1, 13)]
const FIRE: Array[Vector2i] = [Vector2i(8, 10), Vector2i(9, 10), Vector2i(8, 11), Vector2i(9, 11)]
const FUSION: Array[Vector2i] = [Vector2i(0, 25), Vector2i(1, 25), Vector2i(2, 25), Vector2i(0, 26), Vector2i(1, 26), Vector2i(2, 26), Vector2i(0, 27), Vector2i(1, 27), Vector2i(2, 27)]
const GAS: Array[Vector2i] = [Vector2i(8, 21), Vector2i(9, 21), Vector2i(8, 22), Vector2i(9, 22)]
const MICROWAVE: Array[Vector2i] = [Vector2i(8, 19), Vector2i(9, 19), Vector2i(8, 20), Vector2i(9, 20)]
const NUKE: Array[Vector2i] = [Vector2i(2, 12), Vector2i(3, 12), Vector2i(4, 12), Vector2i(2, 13), Vector2i(3, 13), Vector2i(4, 13), Vector2i(2, 14), Vector2i(3, 14), Vector2i(4, 14)]
const OIL: Array[Vector2i] = [Vector2i(6, 23), Vector2i(7, 23), Vector2i(6, 24), Vector2i(7, 24)]
const POLICE: Array[Vector2i] = [Vector2i(6, 10), Vector2i(7, 10), Vector2i(6, 11), Vector2i(7, 11)]
const SEWER_PLANT: Array[Vector2i] = [Vector2i(2, 23), Vector2i(3, 23), Vector2i(2, 24), Vector2i(3, 24)]
const SOLAR: Array[Vector2i] = [Vector2i(4, 23), Vector2i(5, 23), Vector2i(4, 24), Vector2i(5, 24)]
const WATER_PUMP: Array[Vector2i] = [Vector2i(0, 23), Vector2i(1, 23), Vector2i(0, 24), Vector2i(1, 24)]

# Bitmask convention: N=1, E=2, S=4, W=8.
static func road(mask: int) -> Vector2i:
	return Vector2i(mask & 7, 1 + (mask >> 3))
static func rail(mask: int) -> Vector2i:
	return Vector2i(mask & 7, 3 + (mask >> 3))
static func power_line(mask: int) -> Vector2i:
	return Vector2i(mask & 7, 5 + (mask >> 3))
static func shore(mask: int) -> Vector2i:
	return Vector2i(mask & 7, 7 + (mask >> 3))
static func water_pipe(mask: int) -> Vector2i:
	return Vector2i(mask & 7, 19 + (mask >> 3))
static func sewer_pipe(mask: int) -> Vector2i:
	return Vector2i(mask & 7, 21 + (mask >> 3))

# Multi-cell helpers: look up atlas coord by (kind, sub_index).
static func multi(kind_array: Array[Vector2i], sub: int) -> Vector2i:
	return kind_array[sub]
